// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_employee_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_employee_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_employee_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_employee_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_employee_2eproto;
class Employee;
class EmployeeDefaultTypeInternal;
extern EmployeeDefaultTypeInternal _Employee_default_instance_;
class EmployeeList;
class EmployeeListDefaultTypeInternal;
extern EmployeeListDefaultTypeInternal _EmployeeList_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Employee* Arena::CreateMaybeMessage<::Employee>(Arena*);
template<> ::EmployeeList* Arena::CreateMaybeMessage<::EmployeeList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Employee PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Employee) */ {
 public:
  inline Employee() : Employee(nullptr) {};
  virtual ~Employee();

  Employee(const Employee& from);
  Employee(Employee&& from) noexcept
    : Employee() {
    *this = ::std::move(from);
  }

  inline Employee& operator=(const Employee& from) {
    CopyFrom(from);
    return *this;
  }
  inline Employee& operator=(Employee&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Employee& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Employee* internal_default_instance() {
    return reinterpret_cast<const Employee*>(
               &_Employee_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Employee& a, Employee& b) {
    a.Swap(&b);
  }
  inline void Swap(Employee* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Employee* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Employee* New() const final {
    return CreateMaybeMessage<Employee>(nullptr);
  }

  Employee* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Employee>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Employee& from);
  void MergeFrom(const Employee& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Employee* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Employee";
  }
  protected:
  explicit Employee(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_employee_2eproto);
    return ::descriptor_table_employee_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kDepartmentFieldNumber = 3,
    kIdFieldNumber = 1,
    kSalaryFieldNumber = 4,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string department = 3;
  void clear_department();
  const std::string& department() const;
  void set_department(const std::string& value);
  void set_department(std::string&& value);
  void set_department(const char* value);
  void set_department(const char* value, size_t size);
  std::string* mutable_department();
  std::string* release_department();
  void set_allocated_department(std::string* department);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_department();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_department(
      std::string* department);
  private:
  const std::string& _internal_department() const;
  void _internal_set_department(const std::string& value);
  std::string* _internal_mutable_department();
  public:

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // float salary = 4;
  void clear_salary();
  float salary() const;
  void set_salary(float value);
  private:
  float _internal_salary() const;
  void _internal_set_salary(float value);
  public:

  // @@protoc_insertion_point(class_scope:Employee)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr department_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  float salary_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_employee_2eproto;
};
// -------------------------------------------------------------------

class EmployeeList PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:EmployeeList) */ {
 public:
  inline EmployeeList() : EmployeeList(nullptr) {};
  virtual ~EmployeeList();

  EmployeeList(const EmployeeList& from);
  EmployeeList(EmployeeList&& from) noexcept
    : EmployeeList() {
    *this = ::std::move(from);
  }

  inline EmployeeList& operator=(const EmployeeList& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmployeeList& operator=(EmployeeList&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EmployeeList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EmployeeList* internal_default_instance() {
    return reinterpret_cast<const EmployeeList*>(
               &_EmployeeList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EmployeeList& a, EmployeeList& b) {
    a.Swap(&b);
  }
  inline void Swap(EmployeeList* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmployeeList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EmployeeList* New() const final {
    return CreateMaybeMessage<EmployeeList>(nullptr);
  }

  EmployeeList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EmployeeList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EmployeeList& from);
  void MergeFrom(const EmployeeList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EmployeeList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "EmployeeList";
  }
  protected:
  explicit EmployeeList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_employee_2eproto);
    return ::descriptor_table_employee_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEmployeesFieldNumber = 1,
  };
  // repeated .Employee employees = 1;
  int employees_size() const;
  private:
  int _internal_employees_size() const;
  public:
  void clear_employees();
  ::Employee* mutable_employees(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Employee >*
      mutable_employees();
  private:
  const ::Employee& _internal_employees(int index) const;
  ::Employee* _internal_add_employees();
  public:
  const ::Employee& employees(int index) const;
  ::Employee* add_employees();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Employee >&
      employees() const;

  // @@protoc_insertion_point(class_scope:EmployeeList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Employee > employees_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_employee_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Employee

// int32 id = 1;
inline void Employee::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Employee::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Employee::id() const {
  // @@protoc_insertion_point(field_get:Employee.id)
  return _internal_id();
}
inline void Employee::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void Employee::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Employee.id)
}

// string name = 2;
inline void Employee::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Employee::name() const {
  // @@protoc_insertion_point(field_get:Employee.name)
  return _internal_name();
}
inline void Employee::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:Employee.name)
}
inline std::string* Employee::mutable_name() {
  // @@protoc_insertion_point(field_mutable:Employee.name)
  return _internal_mutable_name();
}
inline const std::string& Employee::_internal_name() const {
  return name_.Get();
}
inline void Employee::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Employee::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Employee.name)
}
inline void Employee::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:Employee.name)
}
inline void Employee::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Employee.name)
}
inline std::string* Employee::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Employee::release_name() {
  // @@protoc_insertion_point(field_release:Employee.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Employee::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Employee.name)
}
inline std::string* Employee::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Employee.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Employee::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Employee.name)
}

// string department = 3;
inline void Employee::clear_department() {
  department_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Employee::department() const {
  // @@protoc_insertion_point(field_get:Employee.department)
  return _internal_department();
}
inline void Employee::set_department(const std::string& value) {
  _internal_set_department(value);
  // @@protoc_insertion_point(field_set:Employee.department)
}
inline std::string* Employee::mutable_department() {
  // @@protoc_insertion_point(field_mutable:Employee.department)
  return _internal_mutable_department();
}
inline const std::string& Employee::_internal_department() const {
  return department_.Get();
}
inline void Employee::_internal_set_department(const std::string& value) {
  
  department_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Employee::set_department(std::string&& value) {
  
  department_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Employee.department)
}
inline void Employee::set_department(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  department_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:Employee.department)
}
inline void Employee::set_department(const char* value,
    size_t size) {
  
  department_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Employee.department)
}
inline std::string* Employee::_internal_mutable_department() {
  
  return department_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Employee::release_department() {
  // @@protoc_insertion_point(field_release:Employee.department)
  return department_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Employee::set_allocated_department(std::string* department) {
  if (department != nullptr) {
    
  } else {
    
  }
  department_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), department,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Employee.department)
}
inline std::string* Employee::unsafe_arena_release_department() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Employee.department)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return department_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Employee::unsafe_arena_set_allocated_department(
    std::string* department) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (department != nullptr) {
    
  } else {
    
  }
  department_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      department, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Employee.department)
}

// float salary = 4;
inline void Employee::clear_salary() {
  salary_ = 0;
}
inline float Employee::_internal_salary() const {
  return salary_;
}
inline float Employee::salary() const {
  // @@protoc_insertion_point(field_get:Employee.salary)
  return _internal_salary();
}
inline void Employee::_internal_set_salary(float value) {
  
  salary_ = value;
}
inline void Employee::set_salary(float value) {
  _internal_set_salary(value);
  // @@protoc_insertion_point(field_set:Employee.salary)
}

// -------------------------------------------------------------------

// EmployeeList

// repeated .Employee employees = 1;
inline int EmployeeList::_internal_employees_size() const {
  return employees_.size();
}
inline int EmployeeList::employees_size() const {
  return _internal_employees_size();
}
inline void EmployeeList::clear_employees() {
  employees_.Clear();
}
inline ::Employee* EmployeeList::mutable_employees(int index) {
  // @@protoc_insertion_point(field_mutable:EmployeeList.employees)
  return employees_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Employee >*
EmployeeList::mutable_employees() {
  // @@protoc_insertion_point(field_mutable_list:EmployeeList.employees)
  return &employees_;
}
inline const ::Employee& EmployeeList::_internal_employees(int index) const {
  return employees_.Get(index);
}
inline const ::Employee& EmployeeList::employees(int index) const {
  // @@protoc_insertion_point(field_get:EmployeeList.employees)
  return _internal_employees(index);
}
inline ::Employee* EmployeeList::_internal_add_employees() {
  return employees_.Add();
}
inline ::Employee* EmployeeList::add_employees() {
  // @@protoc_insertion_point(field_add:EmployeeList.employees)
  return _internal_add_employees();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Employee >&
EmployeeList::employees() const {
  // @@protoc_insertion_point(field_list:EmployeeList.employees)
  return employees_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_employee_2eproto
